apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - node-daemonset.yaml
  - node-serviceaccount.yaml
  - csidriver.yaml
  - controller-deployment.yaml
  - controller-serviceaccount.yaml
images:
  - name: amazon/aws-efs-csi-driver
    newTag: v1.6.0
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.10.0-eks-1-27-3
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.8.0-eks-1-27-3
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v3.5.0-eks-1-27-3
